// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package redmine

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD13a9ad4DecodeGithubComSomniSomGoRedmine(in *jlexer.Lexer, out *issuePrioritiesResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "issue_priorities":
			if in.IsNull() {
				in.Skip()
				out.IssuePriorities = nil
			} else {
				in.Delim('[')
				if out.IssuePriorities == nil {
					if !in.IsDelim(']') {
						out.IssuePriorities = make([]IssuePriority, 0, 2)
					} else {
						out.IssuePriorities = []IssuePriority{}
					}
				} else {
					out.IssuePriorities = (out.IssuePriorities)[:0]
				}
				for !in.IsDelim(']') {
					var v1 IssuePriority
					(v1).UnmarshalEasyJSON(in)
					out.IssuePriorities = append(out.IssuePriorities, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD13a9ad4EncodeGithubComSomniSomGoRedmine(out *jwriter.Writer, in issuePrioritiesResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"issue_priorities\":"
		out.RawString(prefix[1:])
		if in.IssuePriorities == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.IssuePriorities {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v issuePrioritiesResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD13a9ad4EncodeGithubComSomniSomGoRedmine(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v issuePrioritiesResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD13a9ad4EncodeGithubComSomniSomGoRedmine(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *issuePrioritiesResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD13a9ad4DecodeGithubComSomniSomGoRedmine(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *issuePrioritiesResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD13a9ad4DecodeGithubComSomniSomGoRedmine(l, v)
}
func easyjsonD13a9ad4DecodeGithubComSomniSomGoRedmine1(in *jlexer.Lexer, out *IssuePriority) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "is_default":
			out.IsDefault = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD13a9ad4EncodeGithubComSomniSomGoRedmine1(out *jwriter.Writer, in IssuePriority) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"is_default\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsDefault))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v IssuePriority) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD13a9ad4EncodeGithubComSomniSomGoRedmine1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v IssuePriority) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD13a9ad4EncodeGithubComSomniSomGoRedmine1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *IssuePriority) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD13a9ad4DecodeGithubComSomniSomGoRedmine1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *IssuePriority) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD13a9ad4DecodeGithubComSomniSomGoRedmine1(l, v)
}
