// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package redmine

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson44273644DecodeGoRedmine(in *jlexer.Lexer, out *timeEntryActivitiesResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "time_entry_activities":
			if in.IsNull() {
				in.Skip()
				out.TimeEntryActivites = nil
			} else {
				in.Delim('[')
				if out.TimeEntryActivites == nil {
					if !in.IsDelim(']') {
						out.TimeEntryActivites = make([]TimeEntryActivity, 0, 2)
					} else {
						out.TimeEntryActivites = []TimeEntryActivity{}
					}
				} else {
					out.TimeEntryActivites = (out.TimeEntryActivites)[:0]
				}
				for !in.IsDelim(']') {
					var v1 TimeEntryActivity
					(v1).UnmarshalEasyJSON(in)
					out.TimeEntryActivites = append(out.TimeEntryActivites, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson44273644EncodeGoRedmine(out *jwriter.Writer, in timeEntryActivitiesResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"time_entry_activities\":"
		out.RawString(prefix[1:])
		if in.TimeEntryActivites == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.TimeEntryActivites {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v timeEntryActivitiesResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson44273644EncodeGoRedmine(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v timeEntryActivitiesResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson44273644EncodeGoRedmine(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *timeEntryActivitiesResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson44273644DecodeGoRedmine(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *timeEntryActivitiesResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson44273644DecodeGoRedmine(l, v)
}
func easyjson44273644DecodeGoRedmine1(in *jlexer.Lexer, out *TimeEntryActivity) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "is_default":
			out.IsDefault = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson44273644EncodeGoRedmine1(out *jwriter.Writer, in TimeEntryActivity) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"is_default\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsDefault))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TimeEntryActivity) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson44273644EncodeGoRedmine1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TimeEntryActivity) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson44273644EncodeGoRedmine1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TimeEntryActivity) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson44273644DecodeGoRedmine1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TimeEntryActivity) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson44273644DecodeGoRedmine1(l, v)
}
