// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package redmine

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson69ff459fDecodeGoRedmine(in *jlexer.Lexer, out *trackersResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "trackers":
			if in.IsNull() {
				in.Skip()
				out.Trackers = nil
			} else {
				in.Delim('[')
				if out.Trackers == nil {
					if !in.IsDelim(']') {
						out.Trackers = make([]IdName, 0, 2)
					} else {
						out.Trackers = []IdName{}
					}
				} else {
					out.Trackers = (out.Trackers)[:0]
				}
				for !in.IsDelim(']') {
					var v1 IdName
					(v1).UnmarshalEasyJSON(in)
					out.Trackers = append(out.Trackers, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson69ff459fEncodeGoRedmine(out *jwriter.Writer, in trackersResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"trackers\":"
		out.RawString(prefix[1:])
		if in.Trackers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Trackers {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v trackersResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson69ff459fEncodeGoRedmine(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v trackersResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson69ff459fEncodeGoRedmine(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *trackersResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson69ff459fDecodeGoRedmine(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *trackersResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson69ff459fDecodeGoRedmine(l, v)
}
